### ISSUE TITLE
Prefix without Space.

### ISSUE THREAD

**Issue by zutsume** [MeLlamoPablo/clapp#1]
First of all thanks for the awesome piece of software, it's solid!

It would be great if you could place the separator as a setting ( the space ) so that a command can have a prefix "/" and the command goes immediately after, without space separating.

For example:

```/command```

**Comment by MeLlamoPablo** [comment]
Hey there! I've released version 1.0.0, which solves this issue, along with many other changes. In your app options object, add the `separator` property, and set it to `''` (empty string). [More info in the docs](https://mellamopablo.github.io/clapp/clapp/1.0.0/App.html).

Please note that version 1.0.0 is a major update, and the old API is incompatible with the new one; you need to make a few changes to your code for Clapp to work, which are documented [here](https://mellamopablo.github.io/clapp/clapp/1.0.0/tutorial-v1-changes.html) (under API changes).

If you came from [generator-discordbot](https://github.com/MeLlamoPablo/generator-discordbot), you also need to modify the `./lib/modules/clapp-discord/index.js` file to make it compatible with the new API. The changes you'd need to make can be found in this [diff](https://github.com/MeLlamoPablo/generator-discordbot/commit/c06566c864aa684ccb5847c79790bad298fe83c4#diff-3eba34a34c3631113de225cb00eac1f5).

Thanks for your feedback; I'm glad this module is helpful! :)

**Comment by Codingale** [comment]
Help command still has a hard coded prefix for the help information etc.

**Comment by MeLlamoPablo** [comment]
@Codingale what do you propose? My intention was to emulate the behavior of bash commands, where `--help` option is pretty much a standard. I guess a `helpFlagName` option (or similar) could be added to the App constructor, but I honestly see no point in it. What value would you use instead?

**Comment by Codingale** [comment]
No, I mostly meant that there was a reference to ` this.prefix + " " + str.help_command `

https://github.com/MeLlamoPablo/clapp/blob/master/dist/App.js#L422

Though the --help option is also effected. I modified my code to just remove the help command like that. I instead used something like `!foo --help` to call `this.getHelp()` which is defined inside of the constructor like:

```js
module.exports = new Clapp.Command({
  name: "foo",
  desc: "bar.",
  fn: (argv, context) => {
    // This output will be redirected to your app's onReply function
    return "baz";
  },
  args: [
    {
      name: 'testarg',
      desc: 'A test argument',
      type: 'string',
      required: false,
      default: ''
    }
  ],
  flags: [
    {
      name: 'testflag',
      desc: 'A test flag',
      alias: 't',
      type: 'boolean',
      default: false
    }
  ],
  getHelp : function(){
      return "Generates a random dog.";
  }
});
```

Don't listen to me to direct you, I don't code very much in NodeJS and very new to discord bots and actually discord in general. I modified it locally just for my own personal use though.

Just thought I'd point out the help command doesn't reference the separator.

**Comment by MeLlamoPablo** [comment]
You're right. I'll fix that when I can. Thanks for pointing out, and don't worry about being new, we've all been there :) I still have a lot to learn as well.

By the way, I don't know if you actually modified the `dist` folder but you're not supposed to do so. The source code is in `lib`, which is transpiled to `dist` by running the command `gulp prepublish`. It still works, but the code in `lib` is much cleaner. I haven't dared to even look at `dist`
