### ISSUE TITLE
Command.args ordering relying on undocumented behaviour

### ISSUE THREAD

**Issue by glorat** [MeLlamoPablo/clapp#15]
If I am reading the code correct, Command is correctly taking in an array of arguments that are necessarily ordered. However, the implementation then puts those args into a map in the for block of line 122 of Command.js, which is technically unordered.

During the parsing in line 258 of App.js, we call
`for (let i in cmd.args) {`
which iterates through the args object, thus relying on the implementation specific behaviour that for/in will "usually" return args in the order they were added but is not specified to necessarily do so.

If I've read this right, the fix would be to maintain args as an array in Command.

p.s. Many thanks for this library! The auto-documentation/auto-validation are awesome

**Comment by MeLlamoPablo** [comment]
Seems like an oversight. Thanks for bringing this to my attention; I'll get on it whenever I can.
