### ISSUE TITLE
Suggestion: Define whether a command, argument or flag is case sensitive.

### ISSUE THREAD

**Issue by ghost** [MeLlamoPablo/clapp#5]
Suggestion: Define whether a command, argument or flag is case sensitive.
For example I might have a command `mycommand` but the user always enters `myCommand` instead of `mycommand`. perhaps there could be a way of defining a command, argument or flag as case sensitive or not to avoid these problems.

**Comment by MeLlamoPablo** [comment]
Sounds like a cool idea. I'll get on it.

**Comment by Sir-Will** [comment]
How do you set a command case insensitive now? I couldn't find anything in the docs.

**Comment by MeLlamoPablo** [comment]
The caseSensitive option is documented here:

https://mellamopablo.github.io/clapp/clapp/1.3.0/Command.html

**Comment by Sir-Will** [comment]
Ah thanks, I think I had a different version of the docs open.
